version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: backend-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build: .
    container_name: backend-nest
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydatabase?schema=public
      - NODE_ENV=development
      - JWT_SECRET=seu_jwt_secret_aqui
      - JWT_EXPIRATION=1d
      - PORT=8000
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
